app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^members$', views.members, name='members'),
    url(r'^alumni$', views.alumni, name='alumni'),
    url(r'^rep$', views.rep, name='rep'),
    url(r'^events$', views.events, name='events'),
    url(r'^gallery$', views.gallery, name='gallery'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^singer/(?P<id>\d+)$', views.singer, name='singer'),
    url(r'^semester/(?P<id>\d+)$', views.semester, name='semester'),

]

myproject/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^app/', include('app.urls',namespace="app")),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/index.html
{% load staticfiles %}
<html>
	<head>
		<title>UNC Tarpeggios A Cappella</title>
		<style type="text/css">
			body {
				background-color: black;
				background-image: url('http://tarpeggios.com/2014/Sky.jpg');
				background-attachment: fixed;
				background-size: cover;
				background-repeat: repeat-x;
				font-family: Trebuchet MS;
				background-size: 100%;
				padding: 0px;
				margin: 0px;
				color: white;
				min-width: 1000px;
			}
			#gradient {
				background: black;
				width: 100%;
				color: white;
				height: 50px;
				  background: -moz-linear-gradient(bottom, #000000 0%, transparent 100%);
				  background: -webkit-linear-gradient(bottom, #000000 5%,transparent 95%);
				  background: -o-linear-gradient(bottom, #FFFFFF 0%,transparent 100%);
				  background: -ms-linear-gradient(bottom, #FFFFFF 0%,transparent 100%);
				  background: linear-gradient(bottom, #FFFFFF 0%,transparent 100%);
			}
			#wrapper {
				width: 100%;
				background: black;
				color: white;
				margin:0px;
				display: table;
				padding-bottom: 80px;
			}
			
			#logo {
				text-align: center;
				padding-top: 0px;
				padding-bottom: 40px;
				background: -moz-linear-gradient(bottom, #000000 0%, transparent 100%);
				background: -webkit-linear-gradient(bottom, #000000 15%,transparent 75%);
				background: -o-linear-gradient(bottom, #FFFFFF 0%,transparent 100%);
				background: -ms-linear-gradient(bottom, #FFFFFF 0%,transparent 100%);
				background: linear-gradient(bottom, #FFFFFF 0%,transparent 100%);
				color: white;
			}
			#logo img {
				width: 30%;
				margin-bottom: 40px;
			}
			#sidebar{
				width: 200px;
    			display: table-cell;
				margin-left: 40px;
				font-size: 10pt;
				padding-left: 15px;
				float:left;
			}
			#sidebar p {
				text-align: justify; 
				padding-bottom: 7px;
			}
			#sidebar h3 {
				padding:0px;
				margin:0px;
				margin-bottom: 2px;
			}
			#main{
				padding-left: 30px;
				display: table-cell;
				padding-right: 15px;

			}
			#logo ul {
				list-style-type: none;
				margin: 0;
				padding: 0;
				letter-spacing: 2px;
			}
			#logo li{
			    display: inline;
			}
			a:link, a:visited, a:active {
				color: white;

			}
			a:hover {
				color: #2A4C7D;
			}
			#main table {
				background: #101011;
				border: 3px solid #101D30;
				padding: 10px;
				width: 700px;

			}
			#main table th{
				text-align: left;
				border-bottom: 1px solid white;

			}
			#main p {
				font-size:15px;
			}
			.rep td {
				padding: 3px;
				font-size: 12px;
				vertical-align: middle;
			}
			.rep a:link {
				text-decoration: none;
			}
			#sidebar a:link {
				text-decoration: none;
			}
			h3 {
			text-decoration: none;
			
			}
			ul a:link {
			text-decoration: none;
			}
			#content{
				{{ maxwidth }}
				margin: auto;
			}
			#member {
				height: 170px;
				border: 3px solid #101D30;
				margin-bottom: 20px;
				margin-right: 20px;
				float:left;
				font-size: 11px;
				text-align: center;
   				vertical-align: bottom;
   				position: relative;
			}
			#member img {
				height:170px;
			}
			#member a {
			}
			#memberinfo {
				display:none;
				position: absolute;
				top: 00px; 
				left: 0; 
				width: 100%; 
				height: 60px;
				padding-top: 110px;
				background: rgba(25,25,25,0.7);
				color: white;
			}
			#member a:hover div {
				display:block;
			}
			#member_sem {
				height: 140px;
				border: 3px solid #101D30;
				margin-bottom: 20px;
				margin-right: 20px;
				float:left;
				font-size: 11px;
				text-align: center;
   				vertical-align: bottom;
   				position: relative;
			}
			#member_sem img {
				height:140px;
			}
			#member_sem a {
			}
			#memberinfo_sem {
				display:none;
				position: absolute;
				top: 00px; 
				left: 0; 
				width: 100%; 
				height: 60px;
				padding-top: 80px;
				background: rgba(25,25,25,0.7);
				color: white;
			}
			#member_sem a:hover div {
				display:block;
			}

			#event {
				background: #101011;
				border: 3px solid #101D30;
				padding: 10px;
				margin-bottom:15px;
				padding-bottom:15px;
			}
			#event p {
				font-size:10pt;
			}
			#event h4{
				margin:0px;
			}


		</style>
	</head>
	
	<body>
		<div id="logo">
			<img src="http://tarpeggios.com/2014/Logo.png" >
			<br />
			<ul>
				<li><a href="{% url 'app:index' %}">HOME</a> | </li>
				<li><a href="{% url 'app:members' %}">MEMBERS</a> | </li>
				<li><a href="{% url 'app:rep' %}">REPERTOIRE</a> | </li>
				<li><a href="{% url 'app:events' %}">EVENTS</a> | </li>
				<li><a href="{% url 'app:gallery' %}">GALLERY</a> | </li>
				<li><a href="{% url 'app:contact' %}">CONTACT</a></li>
			</ul>
		</div>
		<!--<div id="gradient">
		</div>-->
		<div id="wrapper">
			<div id="content">
				<div id ="sidebar">
					{% autoescape off %}{{ sidebar }}{% endautoescape %}	

				</div>
				<div id="main">
					{% autoescape off %}{{ text }}{% endautoescape %}
				</div>
			</div>
		</div>
	</body>
</html>

app/templates/app/list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Minimal Django File Upload Example</title>   
    </head>

    <body>
        <!-- List of uploaded documents -->
        {% if documents %}
            <ul>
            {% for document in documents %}
                <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No documents.</p>
        {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url "app:list" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>

            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>

            <p>{{ form.name.label_tag }} {{ form.name.help_text }}</p>

            <p>
                {{ form.name.errors }}
                {{ form.name }}
            </p>
            Make sure the file name isn't dumb before you upload it because you're gonna have to live with it.  </p><p>Also make sure its the same size.</p><p>  And don't give it a dumb name neither!! Don't be a bo-zo
            <p><input type="submit" value="Upload" /></p>
        </form>
        
    </body>

</html> 